version: "3.5"

services:
  exekube:
    build: ./.docker
    working_dir: /exekube
    environment:
      XK_LIVE_DIR: /exekube/live/prod # default folder for common terraform commands
      TF_LOG:
      TF_INPUT: 0
      TF_VAR_gcp_project:
      TF_VAR_gcp_remote_state_bucket:
      TF_VAR_cloudflare_token:
      TF_VAR_cloudflare_domain_zone:
      TF_VAR_chartmuseum_username:
      TF_VAR_chartmuseum_password:
      TF_VAR_jenkins_domain_name:
      TF_VAR_rails_app_domain_name:
      TF_VAR_chartmuseum_domain_name:
      GOOGLE_CREDENTIALS: /exekube/credentials.json
    ports:
      - 8001:8001
    volumes:
      - .:/exekube
      - ./config/helm:/root/.helm
      - ./config/terragrunt:/root/.terragrunt
      - ./config/gcloud:/root/.config/gcloud
      - ./config/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
