version: "3.5"

services:
  exekube:
    build: .
    working_dir: ${TF_WORKDIR}
    environment:
      GOOGLE_CREDENTIALS: /exekube/credentials.json
      TF_LOG:
      CLOUDFLARE_EMAIL:
      CLOUDFLARE_TOKEN:
      CLOUDFLARE_DOMAIN:
    ports:
      - 8003:8001
    volumes:
      - ./vendor/terraform-provider-helm_linux_amd64:/root/.terraform.d/plugins/terraform-provider-helm_v0.5.0
      - .:/exekube
      - ./config/helm:/root/.helm
      - ./config/gcloud:/root/.config/gcloud
      - ./config/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
