version: "3.5"

services:
  exekube:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    working_dir: /exekube
    environment:
      XK_WORKDIR: /exekube/live/kube/ci # default folder for common terraform commands
      GOOGLE_CREDENTIALS: /exekube/credentials.json
      TF_LOG:
      TF_VAR_cloudflare_email:
      TF_VAR_cloudflare_token:
      TF_VAR_cloudflare_domain:
    ports:
      - 8003:8001
    volumes:
      - .:/exekube
      - ./config/helm:/root/.helm
      - ./config/gcloud:/root/.config/gcloud
      - ./config/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
