version: "3.5"

services:
  exekube:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      - GOOGLE_CREDENTIALS=/exekube/kube-admin-credentials.json
    volumes:
      - .:/exekube
      - ./config/gcloud:/root/.config/gcloud
      - ./config/kube:/root/.kube
    working_dir: /exekube
