version: "3.5"

services:
  xk: # "xk" stands for "exekube"
    build:
      context: .
      dockerfile: ./image/Dockerfile
    working_dir: /exekube
    environment:
      GOOGLE_CREDENTIALS: /exekube/credentials.json
    volumes:
      - .:/exekube
      - ./config/gcloud:/root/.config/gcloud # this too
      - ./config/kube:/root/.kube # and this
