version: "3.5"

secrets:
  credentials.json:
    file: ./credentials.json

services:
  exekube:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    working_dir: /exekube
    secrets:
      - credentials.json
    volumes:
      - ./live:/exekube/live
      - ./modules:/exekube/modules
      - ./.terraform:/exekube/.terraform
      - ./config/gcloud:/root/.config/gcloud
      - ./config/kube:/root/.kube
